url: "http://posadasolycanto.com/"
baseurl: ''
title: Posada Sol y Canto
description: > # this means to ignore newlines until "baseurl:"
  Chalets para 5,6,10 y 13 personas divinamente bien equipados. 
  Organiza la logística para paseos, excursiones y visitas a los parques temáticos.  
  Saloncito de juegos para adultos y una churuata grandísima para eventos. 
email: solycantoreservaciones@hotmail.com
timezone: Europe/Paris
keep_files: []
exclude:
  - _app
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - CNAME
  - template.zip
  - package.json
  - package-lock.json
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
  enable_coderay: false
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
collections:
  rooms:
    output: true
