url: "http://posadasolycanto.com/"
baseurl: ''
google_site_verification: U8Yd3QLDJNWgLlro5kuUvnlWdUb1m-y1iBmFE9KzQ6c
title: Posada Sol y Canto
author: Posada Sol y Canto
description: > 
  Chalets para 5,6,10 y 13 personas divinamente bien equipados. 
  Organiza la logística para paseos, excursiones y visitas a los parques temáticos.  
  Saloncito de juegos para adultos y una churuata grandísima para eventos. 
email: solycantoreservaciones@hotmail.com
timezone: Europe/Paris
lang: es_ES
social:
  name: Posada Sol y Canto
  links:
    - https://www.facebook.com/solycantoposada/
    - https://www.instagram.com/posadasolycanto/
keep_files: []
exclude:
  - _app
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - CNAME
  - template.zip
  - package.json
  - package-lock.json
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: 'lsquo,rsquo,ldquo,rdquo'
  enable_coderay: false
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
collections:
  rooms:
    output: true
